# This is a basic workflow to help you get started with Actions

name: Bing Wallpaper

on:
  schedule:
  # 定时执行，Runs at 07:00 UTC (15:00 GMT) every day
    - cron: '0 7 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run Java Application
        run: java -jar target/Wallpaper-jar-with-dependencies.jar
      - name: Commit files
        run: |
         git config --local user.email "git8888@163.com"
         git config --local user.name "ANBA"
         git add .
         git commit -m "update img"
      - name: Push changes
        uses:  ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.MY_GIT_TOKEN }}
            branch: main
      
